### ISSUE TITLE
what is the methodology?

### ISSUE THREAD

**Issue by muatik** [skroutz/turkish_stemmer#4]
hi,

I am curious about the methodology used to stem words. Do you use snowball approach behind or anything else?

**Comment by greenonion** [comment]
hey @muatik 
the stemmer is essentially a series of state machines operating on the input and applying rules described in the [README](https://github.com/skroutz/turkish_stemmer/blob/master/README.md).

Have a look at the source code (start [here](https://github.com/skroutz/turkish_stemmer/blob/master/lib/turkish_stemmer.rb#L35)). The rules are complex but the methodology is simple.

Hope I helped.

**Comment by muatik** [comment]
thanks
